version: "3.9"

services:
  flyway:
    image: flyway/flyway
    container_name: flyway_cajullenge
    command: -url=jdbc:postgresql://db/cajullenge -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db
    networks:
      - cajullenge-network

  db:
    image: postgres:15.2-alpine3.17
    container_name: postgres_cajullenge
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cajullenge
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - cajullenge-network

networks:
  cajullenge-network:
    driver: "bridge"